; PlatformIO Project Configuration File
; ESP32-S3 BLE Beacon (AirTag-like)
; Detected: ESP32-S3 with 8MB PSRAM

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/cu.usbmodem5B140695281
monitor_port = /dev/cu.usbmodem5B140695281
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
    fastled/FastLED@^3.7.0
